
import { AnnouncementStatus, TargetAudience } from '@/types/announcement';
import { ArticleStatus } from '@/types/article';
import { OrganizationType } from '@/types';

// Données mock pour les catégories (typiques du Cameroun)
export const mockCategories = [
  { 
    id: '1', 
    name: 'Vaccination', 
    slug: 'vaccination',
    description: 'Campagnes de vaccination pour enfants et adultes',
    icon: '💉',
    color: '#10b981',
    parentId: null,
    order: 1,
    isActive: true, 
    announcementsCount: 25, 
    articlesCount: 12,
    advicesCount: 8,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-08-10')
  },
  { 
    id: '2', 
    name: 'Dépistage VIH/SIDA', 
    slug: 'depistage-vih',
    description: 'Campagnes de dépistage du VIH/SIDA',
    icon: '🔬',
    color: '#3b82f6',
    parentId: null,
    order: 2,
    isActive: true, 
    announcementsCount: 18, 
    articlesCount: 10,
    advicesCount: 15,
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2023-08-12')
  },
  { 
    id: '3', 
    name: 'Paludisme', 
    slug: 'paludisme',
    description: 'Prévention et traitement du paludisme',
    icon: '🦟',
    color: '#f59e0b',
    parentId: null,
    order: 3,
    isActive: true, 
    announcementsCount: 32, 
    articlesCount: 15,
    advicesCount: 20,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-08-05')
  },
  { 
    id: '4', 
    name: 'Santé Maternelle', 
    slug: 'sante-maternelle',
    description: 'Soins prénatals et postnatals',
    icon: '🤰',
    color: '#ec4899',
    parentId: null,
    order: 4,
    isActive: true, 
    announcementsCount: 15, 
    articlesCount: 8,
    advicesCount: 12,
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2023-08-08')
  },
  { 
    id: '5', 
    name: 'Nutrition Infantile', 
    slug: 'nutrition-infantile',
    description: 'Alimentation équilibrée pour les enfants',
    icon: '👶',
    color: '#8b5cf6',
    parentId: null,
    order: 5,
    isActive: true, 
    announcementsCount: 20, 
    articlesCount: 14,
    advicesCount: 18,
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2023-08-15')
  },
  { 
    id: '6', 
    name: 'Cancer', 
    slug: 'cancer',
    description: 'Dépistage et prévention des cancers',
    icon: '🎗️',
    color: '#ef4444',
    parentId: null,
    order: 6,
    isActive: true, 
    announcementsCount: 12, 
    articlesCount: 9,
    advicesCount: 7,
    createdAt: new Date('2023-06-18'),
    updatedAt: new Date('2023-08-20')
  },
  { 
    id: '7', 
    name: 'Diabète', 
    slug: 'diabete',
    description: 'Prévention et gestion du diabète',
    icon: '🩸',
    color: '#6366f1',
    parentId: null,
    order: 7,
    isActive: true, 
    announcementsCount: 10, 
    articlesCount: 6,
    advicesCount: 9,
    createdAt: new Date('2023-07-22'),
    updatedAt: new Date('2023-08-18')
  },
  { 
    id: '8', 
    name: 'Hypertension', 
    slug: 'hypertension',
    description: 'Prévention et traitement de l\'hypertension',
    icon: '❤️',
    color: '#f97316',
    parentId: null,
    order: 8,
    isActive: true, 
    announcementsCount: 14, 
    articlesCount: 7,
    advicesCount: 11,
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2023-08-25')
  },
  { 
    id: '9', 
    name: 'Planification Familiale', 
    slug: 'planification-familiale',
    description: 'Méthodes de contraception et conseil',
    icon: '👨‍👩‍👧‍👦',
    color: '#14b8a6',
    parentId: null,
    order: 9,
    isActive: true, 
    announcementsCount: 22, 
    articlesCount: 11,
    advicesCount: 16,
    createdAt: new Date('2023-08-05'),
    updatedAt: new Date('2023-08-22')
  },
  { 
    id: '10', 
    name: 'Hygiène', 
    slug: 'hygiene',
    description: 'Pratiques d\'hygiène pour la santé',
    icon: '🧼',
    color: '#84cc16',
    parentId: null,
    order: 10,
    isActive: true, 
    announcementsCount: 16, 
    articlesCount: 13,
    advicesCount: 14,
    createdAt: new Date('2023-08-10'),
    updatedAt: new Date('2023-08-28')
  },
];

// Données mock pour les annonces (campagnes de santé au Cameroun)
export const mockAnnouncements = [
  {
    id: '1',
    organizationId: 'org1',
    title: 'Journée Nationale de Vaccination contre la Poliomyélite',
    slug: 'journee-nationale-vaccination-poliomyelite',
    content: 'Campagne nationale de vaccination contre la poliomyélite pour les enfants de 0 à 5 ans.',
    excerpt: 'Vaccinez vos enfants contre la poliomyélite dans les centres de santé de votre région.',
    featuredImage: 'vaccination-campaign',
    thumbnailImage: 'vaccination-thumb',
    categoryId: '1',
    startDate: '2025-08-15',
    endDate: '2025-08-20',
    targetAudience: [TargetAudience.INFANTS, TargetAudience.CHILDREN],
    isFree: true,
    cost: null,
    capacity: 500,
    registeredCount: 235,
    requiresRegistration: true,
    viewsCount: 1250,
    sharesCount: 87,
    commentsCount: 42,
    reactionsCount: 156,
    notificationsSent: 1200,
    isPinned: true,
    publishedAt: new Date('2025-07-20'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-07-15'),
    updatedAt: new Date('2025-07-20'),
    organization: {
      id: 'org1',
      name: 'Ministère de la Santé Publique',
      logo: 'ministere-sante-logo',
      phone: '+237 222 23 40 14'
    },
    category: { 
      id: '1', 
      name: 'Vaccination',
      slug: 'vaccination'
    },
    location: { 
      id: 'loc1',
      address: 'Centre de Santé de Bonamoussadi', 
      city: 'Douala', 
      region: 'Littoral',
      latitude: 4.0483,
      longitude: 9.7043
    }
  },
  {
    id: '2',
    organizationId: 'org2',
    title: 'Campagne de Dépistage Gratuit du Cancer du Sein',
    slug: 'campagne-depistage-cancer-sein',
    content: 'Campagne de dépistage gratuit du cancer du sein pour les femmes de 25 ans et plus.',
    excerpt: 'Un dépistage précoce peut sauver des vies. Venez faire votre examen gratuitement.',
    featuredImage: 'breast-cancer-screening',
    thumbnailImage: 'breast-cancer-thumb',
    categoryId: '6',
    startDate: '2025-08-18',
    endDate: '2025-08-25',
    targetAudience: [TargetAudience.ADULTS, TargetAudience.ELDERLY, TargetAudience.PREGNANT_WOMEN],
    isFree: true,
    cost: null,
    capacity: 300,
    registeredCount: 187,
    requiresRegistration: true,
    viewsCount: 980,
    sharesCount: 65,
    commentsCount: 38,
    reactionsCount: 124,
    notificationsSent: 900,
    isPinned: false,
    publishedAt: new Date('2025-07-18'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-07-10'),
    updatedAt: new Date('2025-07-18'),
    organization: {
      id: 'org2',
      name: 'Association Camerounaise de Lutte contre le Cancer',
      logo: 'aclc-logo',
      phone: '+237 233 42 11 31'
    },
    category: { 
      id: '6', 
      name: 'Cancer',
      slug: 'cancer'
    },
    location: { 
      id: 'loc2',
      address: 'Hôpital Central de Yaoundé', 
      city: 'Yaoundé', 
      region: 'Centre',
      latitude: 3.8480,
      longitude: 11.5021
    }
  },
  {
    id: '3',
    organizationId: 'org1',
    title: 'Distribution de Moustiquaires Imprégnées',
    slug: 'distribution-moustiquaires-imprimes',
    content: 'Distribution gratuite de moustiquaires imprégnées pour la prévention du paludisme.',
    excerpt: 'Protégez votre famille contre le paludisme avec des moustiquaires imprégnées.',
    featuredImage: 'mosquito-nets',
    thumbnailImage: 'mosquito-nets-thumb',
    categoryId: '3',
    startDate: '2025-08-22',
    endDate: '2025-08-30',
    targetAudience: [TargetAudience.ALL],
    isFree: true,
    cost: null,
    capacity: 1000,
    registeredCount: 678,
    requiresRegistration: false,
    viewsCount: 1450,
    sharesCount: 98,
    commentsCount: 56,
    reactionsCount: 189,
    notificationsSent: 1500,
    isPinned: false,
    publishedAt: new Date('2025-07-25'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-07-20'),
    updatedAt: new Date('2025-07-25'),
    organization: {
      id: 'org1',
      name: 'Ministère de la Santé Publique',
      logo: 'ministere-sante-logo',
      phone: '+237 222 23 40 14'
    },
    category: { 
      id: '3', 
      name: 'Paludisme',
      slug: 'paludisme'
    },
    location: { 
      id: 'loc3',
      address: 'Centre de Santé de Garoua', 
      city: 'Garoua', 
      region: 'Nord',
      latitude: 9.3117,
      longitude: 13.3975
    }
  },
  {
    id: '4',
    organizationId: 'org3',
    title: 'Journées de Consultation Prénatale Gratuite',
    slug: 'journees-consultation-prenatale-gratuite',
    content: 'Consultations prénatales gratuites pour les femmes enceintes des 2ème et 3ème trimestres.',
    excerpt: 'Un suivi régulier pendant la grossesse est essentiel pour la santé de la mère et du bébé.',
    featuredImage: 'prenatal-care',
    thumbnailImage: 'prenatal-care-thumb',
    categoryId: '4',
    startDate: '2025-08-25',
    endDate: '2025-08-27',
    targetAudience: [TargetAudience.PREGNANT_WOMEN],
    isFree: true,
    cost: null,
    capacity: 200,
    registeredCount: 143,
    requiresRegistration: true,
    viewsCount: 780,
    sharesCount: 54,
    commentsCount: 32,
    reactionsCount: 98,
    notificationsSent: 750,
    isPinned: false,
    publishedAt: new Date('2025-07-28'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-07-22'),
    updatedAt: new Date('2025-07-28'),
    organization: {
      id: 'org3',
      name: 'Hôpital Régional de Bafoussam',
      logo: 'hrb-logo',
      phone: '+237 233 33 12 45'
    },
    category: { 
      id: '4', 
      name: 'Santé Maternelle',
      slug: 'sante-maternelle'
    },
    location: { 
      id: 'loc4',
      address: 'Hôpital Régional de Bafoussam', 
      city: 'Bafoussam', 
      region: 'Ouest',
      latitude: 5.4769,
      longitude: 10.4182
    }
  },
  {
    id: '5',
    organizationId: 'org4',
    title: 'Séance de Sensibilisation sur le Diabète',
    slug: 'seance-sensibilisation-diabete',
    content: 'Séance de sensibilisation sur la prévention et la gestion du diabète.',
    excerpt: 'Apprenez à prévenir et à gérer le diabète pour une meilleure qualité de vie.',
    featuredImage: 'diabetes-awareness',
    thumbnailImage: 'diabetes-awareness-thumb',
    categoryId: '7',
    startDate: '2025-08-28',
    endDate: '2025-08-28',
    targetAudience: [TargetAudience.ADULTS, TargetAudience.ELDERLY],
    isFree: true,
    cost: null,
    capacity: 150,
    registeredCount: 89,
    requiresRegistration: false,
    viewsCount: 620,
    sharesCount: 42,
    commentsCount: 28,
    reactionsCount: 76,
    notificationsSent: 600,
    isPinned: false,
    publishedAt: new Date('2025-08-01'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-07-30'),
    updatedAt: new Date('2025-08-01'),
    organization: {
      id: 'org4',
      name: 'Association des Diabétiques du Cameroun',
      logo: 'adc-logo',
      phone: '+237 233 42 56 78'
    },
    category: { 
      id: '7', 
      name: 'Diabète',
      slug: 'diabete'
    },
    location: { 
      id: 'loc5',
      address: 'Centre de Santé de Maroua', 
      city: 'Maroua', 
      region: 'Extrême-Nord',
      latitude: 10.5945,
      longitude: 14.3159
    }
  },
  {
    id: '6',
    organizationId: 'org5',
    title: 'Campagne de Dépistage de l\'Hypertension',
    slug: 'campagne-depistage-hypertension',
    content: 'Campagne de dépistage gratuit de l\'hypertension artérielle pour les adultes de 30 ans et plus.',
    excerpt: 'L\'hypertension est souvent silencieuse. Faites vérifier votre tension artérielle gratuitement.',
    featuredImage: 'blood-pressure-check',
    thumbnailImage: 'blood-pressure-check-thumb',
    categoryId: '8',
    startDate: '2025-09-02',
    endDate: '2025-09-05',
    targetAudience: [TargetAudience.ADULTS, TargetAudience.ELDERLY],
    isFree: true,
    cost: null,
    capacity: 400,
    registeredCount: 234,
    requiresRegistration: false,
    viewsCount: 890,
    sharesCount: 67,
    commentsCount: 41,
    reactionsCount: 112,
    notificationsSent: 850,
    isPinned: false,
    publishedAt: new Date('2025-08-05'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-08-02'),
    updatedAt: new Date('2025-08-05'),
    organization: {
      id: 'org5',
      name: 'Hôpital Régional de Bamenda',
      logo: 'hrb2-logo',
      phone: '+237 233 33 78 90'
    },
    category: { 
      id: '8', 
      name: 'Hypertension',
      slug: 'hypertension'
    },
    location: { 
      id: 'loc6',
      address: 'Hôpital Régional de Bamenda', 
      city: 'Bamenda', 
      region: 'Nord-Ouest',
      latitude: 5.9631,
      longitude: 10.1595
    }
  },
  {
    id: '7',
    organizationId: 'org6',
    title: 'Atelier sur la Nutrition Infantile',
    slug: 'atelier-nutrition-infantile',
    content: 'Atelier sur les bonnes pratiques nutritionnelles pour les enfants de 6 mois à 5 ans.',
    excerpt: 'Une bonne nutrition est essentielle pour la croissance et le développement de votre enfant.',
    featuredImage: 'child-nutrition',
    thumbnailImage: 'child-nutrition-thumb',
    categoryId: '5',
    startDate: '2025-09-08',
    endDate: '2025-09-10',
    targetAudience: [TargetAudience.CHILDREN, TargetAudience.INFANTS],
    isFree: true,
    cost: null,
    capacity: 100,
    registeredCount: 67,
    requiresRegistration: true,
    viewsCount: 720,
    sharesCount: 48,
    commentsCount: 35,
    reactionsCount: 89,
    notificationsSent: 700,
    isPinned: false,
    publishedAt: new Date('2025-08-08'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-08-05'),
    updatedAt: new Date('2025-08-08'),
    organization: {
      id: 'org6',
      name: 'Centre de Promotion de la Nutrition',
      logo: 'cpn-logo',
      phone: '+237 233 33 45 67'
    },
    category: { 
      id: '5', 
      name: 'Nutrition Infantile',
      slug: 'nutrition-infantile'
    },
    location: { 
      id: 'loc7',
      address: 'Centre de Santé d\'Edea', 
      city: 'Edea', 
      region: 'Littoral',
      latitude: 3.8036,
      longitude: 10.1446
    }
  },
  {
    id: '8',
    organizationId: 'org7',
    title: 'Journée de Sensibilisation sur le VIH/SIDA',
    slug: 'journee-sensibilisation-vih-sida',
    content: 'Journée de sensibilisation et de dépistage gratuit du VIH/SIDA.',
    excerpt: 'Le dépistage est le premier pas vers une prise en charge efficace. Faites-vous dépister.',
    featuredImage: 'hiv-awareness',
    thumbnailImage: 'hiv-awareness-thumb',
    categoryId: '2',
    startDate: '2025-09-15',
    endDate: '2025-09-15',
    targetAudience: [TargetAudience.ADULTS, TargetAudience.YOUTH],
    isFree: true,
    cost: null,
    capacity: 500,
    registeredCount: 312,
    requiresRegistration: false,
    viewsCount: 1100,
    sharesCount: 78,
    commentsCount: 46,
    reactionsCount: 134,
    notificationsSent: 1050,
    isPinned: false,
    publishedAt: new Date('2025-08-10'),
    status: AnnouncementStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: new Date('2025-08-08'),
    updatedAt: new Date('2025-08-10'),
    organization: {
      id: 'org7',
      name: 'Coalition Camerounaise contre le SIDA',
      logo: 'ccs-logo',
      phone: '+237 233 42 89 01'
    },
    category: { 
      id: '2', 
      name: 'Dépistage VIH/SIDA',
      slug: 'depistage-vih'
    },
    location: { 
      id: 'loc8',
      address: 'Centre de Santé de Kribi', 
      city: 'Kribi', 
      region: 'Sud',
      latitude: 2.9415,
      longitude: 10.0091
    }
  }
];

// Données mock pour les articles de santé
export const mockArticles = [
  {
    id: '1',
    organizationId: 'org1',
    title: 'Comment prévenir le paludisme pendant la saison des pluies au Cameroun',
    slug: 'prevenir-paludisme-saison-pluies-cameroun',
    content: 'Le paludisme reste l\'une des principales causes de morbidité et de mortalité au Cameroun. Voici des conseils pratiques pour vous protéger pendant la saison des pluies. Utilisez des moustiquaires imprégnées, éliminez les eaux stagnantes autour de votre maison et prenez des traitements préventifs recommandés par les professionnels de santé.',
    excerpt: 'Le paludisme reste l\'une des principales causes de morbidité et de mortalité au Cameroun. Voici des conseils pratiques pour vous protéger.',
    featuredImage: 'malaria-prevention',
    thumbnailImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
    categoryId: '3',
    author: 'Dr. Jean-Marc Tchamda',
    readingTime: 5,
    tags: ['paludisme', 'prévention', 'saison des pluies', 'moustiquaires'],
    viewsCount: 2450,
    sharesCount: 156,
    commentsCount: 18,
    reactionsCount: 142,
    isFeatured: true,
    publishedAt: '2025-08-01',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-25',
    updatedAt: new Date('2025-08-01'),
    organization: {
      id: 'org1',
      name: 'Ministère de la Santé Publique',
      logo: 'ministere-sante-logo',
      phone: '+237 222 23 40 14'
    },
    category: { 
      id: '3', 
      name: 'Paludisme',
      slug: 'paludisme'
    }
  },
  {
    id: '2',
    organizationId: 'org8',
    title: 'L\'importance de la vaccination chez les enfants camerounais',
    slug: 'importance-vaccination-enfants-camerounais',
    content: 'La vaccination est l\'un des moyens les plus efficaces de protéger les enfants contre les maladies infectieuses graves. Au Cameroun, le Programme Élargi de Vaccination (PEV) vise à réduire la mortalité infantile en assurant une couverture vaccinale élevée. Découvrez le calendrier vaccinal recommandé pour vos enfants.',
    excerpt: 'La vaccination est l\'un des moyens les plus efficaces de protéger les enfants contre les maladies infectieuses graves.',
    featuredImage: 'child-vaccination',
    thumbnailImage: 'child-vaccination-thumb',
    categoryId: '1',
    author: 'Dr. Marie Mbarga',
    readingTime: 7,
    tags: ['vaccination', 'enfants', 'PEV', 'calendrier vaccinal'],
    viewsCount: 1820,
    sharesCount: 124,
    commentsCount: 12,
    reactionsCount: 98,
    isFeatured: false,
    publishedAt: '2025-07-28',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-20',
    updatedAt: new Date('2025-07-28'),
    organization: {
      id: 'org8',
      name: 'Centre de Vaccination de Yaoundé',
      logo: 'cvy-logo',
      phone: '+237 222 23 45 67'
    },
    category: { 
      id: '1', 
      name: 'Vaccination',
      slug: 'vaccination'
    }
  },
  {
    id: '3',
    organizationId: 'org9',
    title: 'Alimentation équilibrée : les produits locaux camerounais à privilégier',
    slug: 'alimentation-equilibree-produits-locaux-cameroun',
    content: 'Une alimentation saine et équilibrée est essentielle pour maintenir une bonne santé. Le Cameroun dispose d\'une grande variété de produits locaux riches en nutriments. Découvrez comment composer vos repas avec des produits comme le manioc, le plantain, le gombo, le poisson fumé et bien d\'autres.',
    excerpt: 'Une alimentation saine et équilibrée est essentielle pour maintenir une bonne santé. Découvrez les produits locaux riches en nutriments.',
    featuredImage: 'local-foods',
    thumbnailImage: 'local-foods-thumb',
    categoryId: '5',
    author: 'Dr. Sophie Ngo',
    readingTime: 6,
    tags: ['alimentation', 'produits locaux', 'nutrition', 'manioc', 'plantain'],
    viewsCount: 1650,
    sharesCount: 98,
    commentsCount: 15,
    reactionsCount: 87,
    isFeatured: false,
    publishedAt: '2025-07-25',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-18',
    updatedAt: new Date('2025-07-25'),
    organization: {
      id: 'org9',
      name: 'Institut de Nutrition et de Technologie Alimentaire',
      logo: 'inta-logo',
      phone: '+237 222 23 56 78'
    },
    category: { 
      id: '5', 
      name: 'Nutrition Infantile',
      slug: 'nutrition-infantile'
    }
  },
  {
    id: '4',
    organizationId: 'org1',
    title: 'Comment reconnaître les symptômes du COVID-19 et que faire',
    slug: 'reconnaitre-symptomes-covid-19-cameroun',
    content: 'Le COVID-19 continue de circuler au Cameroun. Il est important de connaître les symptômes et les gestes à adopter en cas de suspicion. Fièvre, toux sèche, fatigue, perte de goût ou d\'odorat sont les symptômes les plus courants. En cas de symptômes, isolez-vous et contactez les services de santé.',
    excerpt: 'Le COVID-19 continue de circuler au Cameroun. Il est important de connaître les symptômes et les gestes à adopter.',
    featuredImage: 'covid-symptoms',
    thumbnailImage: 'covid-symptoms-thumb',
    categoryId: '1',
    author: 'Dr. Pierre Kamga',
    readingTime: 4,
    tags: ['COVID-19', 'symptômes', 'prévention', 'gestes barrière'],
    viewsCount: 2100,
    sharesCount: 167,
    commentsCount: 25,
    reactionsCount: 156,
    isFeatured: true,
    publishedAt: '2025-07-22',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-15',
    updatedAt: new Date('2025-07-22'),
    organization: {
      id: 'org1',
      name: 'Ministère de la Santé Publique',
      logo: 'ministere-sante-logo',
      phone: '+237 222 23 40 14'
    },
    category: { 
      id: '1', 
      name: 'Vaccination',
      slug: 'vaccination'
    }
  },
  {
    id: '5',
    organizationId: 'org10',
    title: 'Santé maternelle : les consultations prénatales au Cameroun',
    slug: 'sante-maternelle-consultations-prenatales-cameroun',
    content: 'Les soins prénatals sont essentiels pour assurer une grossesse saine et réduire les risques de complications. Au Cameroun, il est recommandé de faire au moins 4 consultations prénatales pendant la grossesse. Découvrez ce qui est vérifié lors de ces consultations et pourquoi elles sont importantes.',
    excerpt: 'Les soins prénatals sont essentiels pour assurer une grossesse saine et réduire les risques de complications.',
    featuredImage: 'prenatal-care',
    thumbnailImage: 'prenatal-care-thumb',
    categoryId: '4',
    author: 'Dr. Rachel Essomba',
    readingTime: 8,
    tags: ['santé maternelle', 'consultations prénatales', 'grossesse', 'soins périnataux'],
    viewsCount: 1780,
    sharesCount: 134,
    commentsCount: 20,
    reactionsCount: 112,
    isFeatured: false,
    publishedAt: '2025-07-18',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-10',
    updatedAt: new Date('2025-07-18'),
    organization: {
      id: 'org10',
      name: 'Hôpital Central de Yaoundé',
      logo: 'hcy-logo',
      phone: '+237 222 23 14 52'
    },
    category: { 
      id: '4', 
      name: 'Santé Maternelle',
      slug: 'sante-maternelle'
    }
  },
  {
    id: '6',
    organizationId: 'org11',
    title: 'Les plantes médicinales camerounaises reconnues par la science',
    slug: 'plantes-medicinales-camerounaises-reconnues-science',
    content: 'Le Cameroun possède une riche biodiversité avec de nombreuses plantes aux propriétés médicinales reconnues. Des études scientifiques ont validé l\'efficacité de certaines plantes comme le moringa, l\'artemisia, le neem ou encore le kinkeliba dans le traitement de divers maux.',
    excerpt: 'Le Cameroun possède une riche biodiversité avec de nombreuses plantes aux propriétés médicinales reconnues.',
    featuredImage: 'medicinal-plants',
    thumbnailImage: 'medicinal-plants-thumb',
    categoryId: '9',
    author: 'Dr. Joseph Etame',
    readingTime: 6,
    tags: ['plantes médicinales', 'médecine traditionnelle', 'moringa', 'artemisia'],
    viewsCount: 1920,
    sharesCount: 145,
    commentsCount: 22,
    reactionsCount: 134,
    isFeatured: false,
    publishedAt: '2025-07-15',
    status: ArticleStatus.PUBLISHED,
    suspensionReason: null,
    suspendedBy: null,
    deletedAt: null,
    createdAt: '2025-07-08',
    updatedAt: new Date('2025-07-15'),
    organization: {
      id: 'org11',
      name: 'Institut de Recherche Médicale et d\'Études des Plantes Médicinales',
      logo: 'irempm-logo',
      phone: '+237 222 23 67 89'
    },
    category: { 
      id: '9', 
      name: 'Hygiène',
      slug: 'hygiene'
    }
  }
];
export const mockHospitals = [
  {
    id: '1',
    name: 'Hôpital Central de Yaoundé',
    email: 'info@hcy.cm',
    phone: '+237 222 23 14 52',
    address: 'Avenue Charles Atangana',
    city: 'Yaoundé',
    region: 'Centre',
    country: 'Cameroun',
    logo: 'hcy-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Cardiologie', 'Pédiatrie', 'Gynécologie', 'Urgences 24/7'],
    website: 'https://www.hcy.cm',
    isActive: true,
    isVerified: true,
    latitude: 3.8480,
    longitude: 11.5021,
    rating: 4.2,
    totalReviews: 156, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HCY-2020-001',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS', 'Allianz', 'AXA'],
    openingHours: '24/7',
    description: 'Hôpital de référence pour les maladies cardiaques et pédiatriques',
    createdAt: new Date('2020-01-15'),
    updatedAt: new Date('2023-08-10')
  },
  {
    id: '2',
    name: 'Hôpital Laquintinie de Douala',
    email: 'contact@laquintinie.cm',
    phone: '+237 233 42 11 31',
    address: 'Boulevard de la Liberté',
    city: 'Douala',
    region: 'Littoral',
    country: 'Cameroun',
    logo: 'laquintinie-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Chirurgie', 'Ophtalmologie', 'Urgences 24/7'],
    website: null,
    isActive: true,
    isVerified: true,
    latitude: 4.0483,
    longitude: 9.7043,
    rating: 4.0,
    totalReviews: 142, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HLQ-2019-002',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS', 'Allianz'],
    openingHours: '24/7',
    description: 'Spécialisé en chirurgie et ophtalmologie',
    createdAt: new Date('2019-05-20'),
    updatedAt: new Date('2023-07-22')
  },
  {
    id: '3',
    name: 'Hôpital Général de Douala',
    email: 'info@hgd.cm',
    phone: '+237 233 42 20 11',
    address: 'Rue Joss',
    city: 'Douala',
    region: 'Littoral',
    country: 'Cameroun',
    logo: 'hgd-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Médecine Interne', 'Pédiatrie', 'Urgences 24/7'],
    website: 'https://www.hgd.cm',
    isActive: true,
    isVerified: true,
    latitude: 4.0511,
    longitude: 9.7679,
    rating: 3.8,
    totalReviews: 128, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HGD-2018-003',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS'],
    openingHours: '24/7',
    description: 'Hôpital général avec services de médecine interne et pédiatrie',
    createdAt: new Date('2018-11-10'),
    updatedAt: new Date('2023-08-05')
  },
  {
    id: '4',
    name: 'Hôpital Jamot de Yaoundé',
    email: 'contact@hopital-jamot.cm',
    phone: '+237 222 23 16 01',
    address: 'Rue Mballa II',
    city: 'Yaoundé',
    region: 'Centre',
    country: 'Cameroun',
    logo: 'hopital-jamot-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Pneumologie', 'Cardiologie', 'Urgences 24/7'],
    website: null,
    isActive: true,
    isVerified: true,
    latitude: 3.8660,
    longitude: 11.5185,
    rating: 4.1,
    totalReviews: 167, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HJY-2021-004',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS', 'Allianz', 'AXA'],
    openingHours: '24/7',
    description: 'Spécialisé en pneumologie et cardiologie',
    createdAt: new Date('2021-02-18'),
    updatedAt: new Date('2023-08-15')
  },
  {
    id: '5',
    name: 'Centre Hospitalier et Universitaire (CHU) de Yaoundé',
    email: 'info@chu-yaounde.cm',
    phone: '+237 222 23 40 14',
    address: 'Campus de l\'Université de Yaoundé I',
    city: 'Yaoundé',
    region: 'Centre',
    country: 'Cameroun',
    logo: 'chu-yaounde-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Toutes spécialités', 'Urgences 24/7', 'Formation médicale'],
    website: 'https://www.chu-yaounde.cm',
    isActive: true,
    isVerified: true,
    latitude: 3.8265,
    longitude: 11.4998,
    rating: 4.3,
    totalReviews: 189, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'CHUY-2017-005',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS', 'Allianz', 'AXA', 'Mutuelle des fonctionnaires'],
    openingHours: '24/7',
    description: 'Centre hospitalier universitaire avec toutes les spécialités',
    createdAt: new Date('2017-09-05'),
    updatedAt: new Date('2023-08-20')
  },
  {
    id: '6',
    name: 'Hôpital Régional de Bafoussam',
    email: 'info@hr-bafoussam.cm',
    phone: '+237 233 33 12 45',
    address: 'Avenue des Chutes',
    city: 'Bafoussam',
    region: 'Ouest',
    country: 'Cameroun',
    logo: 'hr-bafoussam-logo.png',
    type: OrganizationType.PUBLIC,
    specialties: ['Médecine Générale', 'Pédiatrie', 'Urgences 24/7'],
    website: null,
    isActive: true,
    isVerified: true,
    latitude: 5.4769,
    longitude: 10.4182,
    rating: 3.7,
    totalReviews: 98, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HRB-2019-006',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS'],
    openingHours: '24/7',
    description: 'Hôpital régional desservant la région de l\'Ouest',
    createdAt: new Date('2019-07-30'),
    updatedAt: new Date('2023-07-10')
  },
  {
    id: '7',
    name: 'Hôpital Ad Lucem de Mbouda',
    email: 'contact@adlucem-mbouda.cm',
    phone: '+237 233 33 56 78',
    address: 'Quartier Chefferie',
    city: 'Mbouda',
    region: 'Ouest',
    country: 'Cameroun',
    logo: 'adlucem-logo.png',
    type: OrganizationType.PRIVATE,
    specialties: ['Chirurgie', 'Gynécologie', 'Urgences'],
    website: 'https://www.adlucem-mbouda.cm',
    isActive: true,
    isVerified: false,
    latitude: 5.6363,
    longitude: 10.2548,
    rating: 3.9,
    totalReviews: 76, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HALM-2020-007',
    emergencyAvailable: false,
    insuranceAccepted: ['Allianz', 'AXA'],
    openingHours: '08:00 - 18:00',
    description: 'Hôpital privé spécialisé en chirurgie et gynécologie',
    createdAt: new Date('2020-03-12'),
    updatedAt: new Date('2023-06-25')
  },
  {
    id: '8',
    name: 'Hôpital Protestant de Ngaoundéré',
    email: 'info@hpn-gaoundere.cm',
    phone: '+237 222 62 12 34',
    address: 'Quartier Djalingo',
    city: 'Ngaoundéré',
    region: 'Adamaoua',
    country: 'Cameroun',
    logo: 'hpn-logo.png',
    type: OrganizationType.PRIVATE,
    specialties: ['Médecine Interne', 'Pédiatrie', 'Urgences 24/7'],
    website: null,
    isActive: true,
    isVerified: true,
    latitude: 7.3158,
    longitude: 13.5785,
    rating: 3.6,
    totalReviews: 84, // Corrigé de reviewsCount à totalReviews
    registrationNumber: 'HPN-2021-008',
    emergencyAvailable: true,
    insuranceAccepted: ['CNPS', 'Mutuelle des fonctionnaires'],
    openingHours: '24/7',
    description: 'Hôpital protestant avec services de médecine interne et pédiatrie',
    createdAt: new Date('2021-10-08'),
    updatedAt: new Date('2023-08-01')
  }
];